--- 
- hosts: localhost
  connection: local
  tasks:
  - name: Create three ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ec2_key"
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      vpc_subnet_id: subnet-0fbecb601757a5482   
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image}}"
      tags:
        Environment: "{{ item.name }}"
    loop:
     - { image: "ami-0f88e80871fd81e91", name: "Node-1" }
     - { image: "ami-084568db4383264d4", name: "Node-2" }
     - { image: "ami-084568db4383264d4", name: "Node-3" }      
